// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import org.ete.fleacircus.client.managed.request.ApplicationEntityTypesProcessor;
import org.ete.fleacircus.client.managed.request.ApplicationRequestFactory;
import org.ete.fleacircus.client.managed.request.EventProxy;
import org.ete.fleacircus.client.managed.request.FleaProxy;
import org.ete.fleacircus.client.managed.request.SpecialtyProxy;
import org.ete.fleacircus.client.managed.ui.EventListView;
import org.ete.fleacircus.client.managed.ui.EventMobileListView;
import org.ete.fleacircus.client.managed.ui.FleaListView;
import org.ete.fleacircus.client.managed.ui.FleaMobileListView;
import org.ete.fleacircus.client.managed.ui.SpecialtyListView;
import org.ete.fleacircus.client.managed.ui.SpecialtyMobileListView;
import org.ete.fleacircus.client.scaffold.ScaffoldApp;
import org.ete.fleacircus.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleSpecialty(SpecialtyProxy isNull) {
                setResult(new SpecialtyListActivity(requests, ScaffoldApp.isMobile() ? SpecialtyMobileListView.instance() : SpecialtyListView.instance(), placeController));
            }

            @Override
            public void handleFlea(FleaProxy isNull) {
                setResult(new FleaListActivity(requests, ScaffoldApp.isMobile() ? FleaMobileListView.instance() : FleaListView.instance(), placeController));
            }

            @Override
            public void handleEvent(EventProxy isNull) {
                setResult(new EventListActivity(requests, ScaffoldApp.isMobile() ? EventMobileListView.instance() : EventListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
