// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import org.ete.fleacircus.client.managed.activity.FleaEditActivityWrapper.View;
import org.ete.fleacircus.client.managed.request.ApplicationRequestFactory;
import org.ete.fleacircus.client.managed.request.FleaProxy;
import org.ete.fleacircus.client.managed.request.SpecialtyProxy;
import org.ete.fleacircus.client.managed.ui.SpecialtySetEditor;
import org.ete.fleacircus.client.scaffold.activity.IsScaffoldMobileActivity;
import org.ete.fleacircus.client.scaffold.place.ProxyEditView;
import org.ete.fleacircus.client.scaffold.place.ProxyListPlace;
import org.ete.fleacircus.client.scaffold.place.ProxyPlace;

public abstract class FleaEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setSpecialtiesPickerValues(Collections.<SpecialtyProxy>emptyList());
        requests.specialtyRequest().findSpecialtyEntries(0, 50).with(org.ete.fleacircus.client.managed.ui.SpecialtyProxyRenderer.instance().getPaths()).fire(new Receiver<List<SpecialtyProxy>>() {

            public void onSuccess(List<SpecialtyProxy> response) {
                List<SpecialtyProxy> values = new ArrayList<SpecialtyProxy>();
                values.add(null);
                values.addAll(response);
                view.setSpecialtiesPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends org.ete.fleacircus.client.scaffold.place.ProxyEditView<org.ete.fleacircus.client.managed.request.FleaProxy, V>> extends ProxyEditView<FleaProxy, V> {

        void setSpecialtiesPickerValues(Collection<SpecialtyProxy> values);
    }
}
