// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import org.ete.fleacircus.client.managed.activity.SpecialtyEditActivityWrapper.View;
import org.ete.fleacircus.client.managed.request.ApplicationRequestFactory;
import org.ete.fleacircus.client.managed.request.FleaProxy;
import org.ete.fleacircus.client.managed.request.SpecialtyProxy;
import org.ete.fleacircus.client.managed.ui.FleaSetEditor;
import org.ete.fleacircus.client.scaffold.activity.IsScaffoldMobileActivity;
import org.ete.fleacircus.client.scaffold.place.ProxyEditView;
import org.ete.fleacircus.client.scaffold.place.ProxyListPlace;
import org.ete.fleacircus.client.scaffold.place.ProxyPlace;

public abstract class SpecialtyEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setFleasPickerValues(Collections.<FleaProxy>emptyList());
        requests.fleaRequest().findFleaEntries(0, 50).with(org.ete.fleacircus.client.managed.ui.FleaProxyRenderer.instance().getPaths()).fire(new Receiver<List<FleaProxy>>() {

            public void onSuccess(List<FleaProxy> response) {
                List<FleaProxy> values = new ArrayList<FleaProxy>();
                values.add(null);
                values.addAll(response);
                view.setFleasPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends org.ete.fleacircus.client.scaffold.place.ProxyEditView<org.ete.fleacircus.client.managed.request.SpecialtyProxy, V>> extends ProxyEditView<SpecialtyProxy, V> {

        void setFleasPickerValues(Collection<FleaProxy> values);
    }
}
