// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.request;

import org.ete.fleacircus.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    SpecialtyRequest specialtyRequest();

    FleaRequest fleaRequest();

    EventRequest eventRequest();
}
