// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.ete.fleacircus.model.Event")
@ServiceName("org.ete.fleacircus.model.Event")
public interface EventRequest extends RequestContext {

    abstract InstanceRequest<org.ete.fleacircus.client.managed.request.EventProxy, java.lang.Void> persist();

    abstract InstanceRequest<org.ete.fleacircus.client.managed.request.EventProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countEvents();

    abstract Request<java.util.List<org.ete.fleacircus.client.managed.request.EventProxy>> findAllEvents();

    abstract Request<org.ete.fleacircus.client.managed.request.EventProxy> findEvent(Long id);

    abstract Request<java.util.List<org.ete.fleacircus.client.managed.request.EventProxy>> findEventEntries(int firstResult, int maxResults);
}
