// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Date;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.ete.fleacircus.model.Event")
@ProxyForName("org.ete.fleacircus.model.Event")
public interface EventProxy extends EntityProxy {

    abstract Date getStartDate();

    abstract void setStartDate(Date startDate);

    abstract Date getEndDate();

    abstract void setEndDate(Date endDate);

    abstract String getName();

    abstract void setName(String name);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);
}
