// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.ete.fleacircus.model.Flea")
@ServiceName("org.ete.fleacircus.model.Flea")
public interface FleaRequest extends RequestContext {

    abstract InstanceRequest<org.ete.fleacircus.client.managed.request.FleaProxy, java.lang.Void> persist();

    abstract InstanceRequest<org.ete.fleacircus.client.managed.request.FleaProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countFleas();

    abstract Request<java.util.List<org.ete.fleacircus.client.managed.request.FleaProxy>> findAllFleas();

    abstract Request<org.ete.fleacircus.client.managed.request.FleaProxy> findFlea(Long id);

    abstract Request<java.util.List<org.ete.fleacircus.client.managed.request.FleaProxy>> findFleaEntries(int firstResult, int maxResults);
}
