// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Set;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.ete.fleacircus.model.Flea")
@ProxyForName("org.ete.fleacircus.model.Flea")
public interface FleaProxy extends EntityProxy {

    abstract String getName();

    abstract void setName(String name);

    abstract Set<org.ete.fleacircus.client.managed.request.SpecialtyProxy> getSpecialties();

    abstract void setSpecialties(Set<SpecialtyProxy> specialties);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);
}
