// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.ete.fleacircus.model.Specialty")
@ServiceName("org.ete.fleacircus.model.Specialty")
public interface SpecialtyRequest extends RequestContext {

    abstract InstanceRequest<org.ete.fleacircus.client.managed.request.SpecialtyProxy, java.lang.Void> persist();

    abstract InstanceRequest<org.ete.fleacircus.client.managed.request.SpecialtyProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countSpecialities();

    abstract Request<java.util.List<org.ete.fleacircus.client.managed.request.SpecialtyProxy>> findAllSpecialities();

    abstract Request<org.ete.fleacircus.client.managed.request.SpecialtyProxy> findSpecialty(Long id);

    abstract Request<java.util.List<org.ete.fleacircus.client.managed.request.SpecialtyProxy>> findSpecialtyEntries(int firstResult, int maxResults);
}
