// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.ui;

import com.google.gwt.text.shared.AbstractRenderer;
import org.ete.fleacircus.client.managed.request.ApplicationEntityTypesProcessor;
import org.ete.fleacircus.client.managed.request.EventProxy;
import org.ete.fleacircus.client.managed.request.FleaProxy;
import org.ete.fleacircus.client.managed.request.SpecialtyProxy;
import org.ete.fleacircus.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleSpecialty(SpecialtyProxy isNull) {
                setResult("Specialtys");
            }

            @Override
            public void handleFlea(FleaProxy isNull) {
                setResult("Fleas");
            }

            @Override
            public void handleEvent(EventProxy isNull) {
                setResult("Events");
            }
        }.process(object.getProxyClass());
    }
}
