// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import org.ete.fleacircus.client.managed.request.EventProxy;
import org.ete.fleacircus.client.scaffold.place.ProxyDetailsView;
import org.ete.fleacircus.client.scaffold.place.ProxyListView;

public abstract class EventDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<EventProxy> {

    @UiField
    SpanElement startDate;

    @UiField
    SpanElement endDate;

    @UiField
    SpanElement name;

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    EventProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(EventProxy proxy) {
        this.proxy = proxy;
        startDate.setInnerText(proxy.getStartDate() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getStartDate()));
        endDate.setInnerText(proxy.getEndDate() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getEndDate()));
        name.setInnerText(proxy.getName() == null ? "" : String.valueOf(proxy.getName()));
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(org.ete.fleacircus.client.managed.ui.EventProxyRenderer.instance().render(proxy));
    }
}
