// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.ui;

import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.safehtml.shared.SafeHtml;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.safehtml.shared.SafeHtmlUtils;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.AbstractSafeHtmlRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.text.shared.SafeHtmlRenderer;
import java.util.HashSet;
import java.util.Set;
import org.ete.fleacircus.client.managed.request.EventProxy;
import org.ete.fleacircus.client.scaffold.ScaffoldMobileApp;
import org.ete.fleacircus.client.scaffold.ui.MobileProxyListView;

public abstract class EventMobileListView_Roo_Gwt extends MobileProxyListView<EventProxy> {

    protected Set<String> paths = new HashSet<String>();

    public EventMobileListView_Roo_Gwt(String buttonText, SafeHtmlRenderer<org.ete.fleacircus.client.managed.request.EventProxy> renderer) {
        super(buttonText, renderer);
    }

    public void init() {
        paths.add("name");
        paths.add("startDate");
        paths.add("startDate");
    }
}
