// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.Set;
import org.ete.fleacircus.client.managed.request.FleaProxy;
import org.ete.fleacircus.client.managed.request.SpecialtyProxy;
import org.ete.fleacircus.client.scaffold.place.ProxyDetailsView;
import org.ete.fleacircus.client.scaffold.place.ProxyListView;

public abstract class SpecialtyDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<SpecialtyProxy> {

    @UiField
    SpanElement name;

    @UiField
    SpanElement fleas;

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    SpecialtyProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(SpecialtyProxy proxy) {
        this.proxy = proxy;
        name.setInnerText(proxy.getName() == null ? "" : String.valueOf(proxy.getName()));
        fleas.setInnerText(proxy.getFleas() == null ? "" : org.ete.fleacircus.client.scaffold.place.CollectionRenderer.of(org.ete.fleacircus.client.managed.ui.FleaProxyRenderer.instance()).render(proxy.getFleas()));
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(org.ete.fleacircus.client.managed.ui.SpecialtyProxyRenderer.instance().render(proxy));
    }
}
