// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.ete.fleacircus.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import org.ete.fleacircus.client.managed.request.FleaProxy;
import org.ete.fleacircus.client.managed.request.SpecialtyProxy;
import org.ete.fleacircus.client.scaffold.place.AbstractProxyListView;

public abstract class SpecialtyListView_Roo_Gwt extends AbstractProxyListView<SpecialtyProxy> {

    @UiField
    CellTable<SpecialtyProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("name");
        table.addColumn(new TextColumn<SpecialtyProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(SpecialtyProxy object) {
                return renderer.render(object.getName());
            }
        }, "Name");
        paths.add("fleas");
        table.addColumn(new TextColumn<SpecialtyProxy>() {

            Renderer<java.util.Set> renderer = org.ete.fleacircus.client.scaffold.place.CollectionRenderer.of(org.ete.fleacircus.client.managed.ui.FleaProxyRenderer.instance());

            @Override
            public String getValue(SpecialtyProxy object) {
                return renderer.render(object.getFleas());
            }
        }, "Fleas");
        paths.add("id");
        table.addColumn(new TextColumn<SpecialtyProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(SpecialtyProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("version");
        table.addColumn(new TextColumn<SpecialtyProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(SpecialtyProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
    }
}
