// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.ete.fleacircus.model;

import java.io.Serializable;

privileged aspect MessageCommand_Roo_Serializable {
    
    declare parents: MessageCommand implements Serializable;
    
    private static final long MessageCommand.serialVersionUID = 1L;
    
}
