// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.ete.fleacircus.model;

import java.lang.String;

privileged aspect MessageCommand_Roo_JavaBean {
    
    public String MessageCommand.getMessage() {
        return this.message;
    }
    
    public void MessageCommand.setMessage(String message) {
        this.message = message;
    }
    
}
