// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.ete.fleacircus.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EventsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EventsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EventsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EventsIntegrationTest: @Transactional;
    
    @Autowired
    private EventsDataOnDemand EventsIntegrationTest.dod;
    
    @Test
    public void EventsIntegrationTest.testCountEventses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to initialize correctly", dod.getRandomEvents());
        long count = Event.countEventses();
        org.junit.Assert.assertTrue("Counter for 'Event' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EventsIntegrationTest.testFindEvents() {
        Event obj = dod.getRandomEvents();
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to provide an identifier", id);
        obj = Event.findEvents(id);
        org.junit.Assert.assertNotNull("Find method for 'Event' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Event' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EventsIntegrationTest.testFindAllEventses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to initialize correctly", dod.getRandomEvents());
        long count = Event.countEventses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Event', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<Event> result = Event.findAllEventses();
        org.junit.Assert.assertNotNull("Find all method for 'Event' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Event' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EventsIntegrationTest.testFindEventsEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to initialize correctly", dod.getRandomEvents());
        long count = Event.countEventses();
        if (count > 20) count = 20;
        java.util.List<Event> result = Event.findEventsEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Event' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Event' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EventsIntegrationTest.testFlush() {
        Event obj = dod.getRandomEvents();
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to provide an identifier", id);
        obj = Event.findEvents(id);
        org.junit.Assert.assertNotNull("Find method for 'Event' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEvents(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Event' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventsIntegrationTest.testMerge() {
        Event obj = dod.getRandomEvents();
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to provide an identifier", id);
        obj = Event.findEvents(id);
        boolean modified =  dod.modifyEvents(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        Event merged = (Event) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Event' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventsIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to initialize correctly", dod.getRandomEvents());
        Event obj = dod.getNewTransientEvents(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Event' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Event' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EventsIntegrationTest.testRemove() {
        Event obj = dod.getRandomEvents();
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Event' failed to provide an identifier", id);
        obj = Event.findEvents(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Event' with identifier '" + id + "'", Event.findEvents(id));
    }
    
}
