// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.ete.fleacircus.model;

import org.ete.fleacircus.model.FleaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FleaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FleaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FleaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FleaIntegrationTest: @Transactional;
    
    @Autowired
    private FleaDataOnDemand FleaIntegrationTest.dod;
    
    @Test
    public void FleaIntegrationTest.testCountFleas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to initialize correctly", dod.getRandomFlea());
        long count = org.ete.fleacircus.model.Flea.countFleas();
        org.junit.Assert.assertTrue("Counter for 'Flea' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FleaIntegrationTest.testFindFlea() {
        org.ete.fleacircus.model.Flea obj = dod.getRandomFlea();
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to provide an identifier", id);
        obj = org.ete.fleacircus.model.Flea.findFlea(id);
        org.junit.Assert.assertNotNull("Find method for 'Flea' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Flea' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FleaIntegrationTest.testFindAllFleas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to initialize correctly", dod.getRandomFlea());
        long count = org.ete.fleacircus.model.Flea.countFleas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Flea', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.ete.fleacircus.model.Flea> result = org.ete.fleacircus.model.Flea.findAllFleas();
        org.junit.Assert.assertNotNull("Find all method for 'Flea' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Flea' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FleaIntegrationTest.testFindFleaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to initialize correctly", dod.getRandomFlea());
        long count = org.ete.fleacircus.model.Flea.countFleas();
        if (count > 20) count = 20;
        java.util.List<org.ete.fleacircus.model.Flea> result = org.ete.fleacircus.model.Flea.findFleaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Flea' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Flea' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FleaIntegrationTest.testFlush() {
        org.ete.fleacircus.model.Flea obj = dod.getRandomFlea();
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to provide an identifier", id);
        obj = org.ete.fleacircus.model.Flea.findFlea(id);
        org.junit.Assert.assertNotNull("Find method for 'Flea' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFlea(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Flea' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FleaIntegrationTest.testMerge() {
        org.ete.fleacircus.model.Flea obj = dod.getRandomFlea();
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to provide an identifier", id);
        obj = org.ete.fleacircus.model.Flea.findFlea(id);
        boolean modified =  dod.modifyFlea(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.ete.fleacircus.model.Flea merged = (org.ete.fleacircus.model.Flea) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Flea' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FleaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to initialize correctly", dod.getRandomFlea());
        org.ete.fleacircus.model.Flea obj = dod.getNewTransientFlea(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Flea' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Flea' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FleaIntegrationTest.testRemove() {
        org.ete.fleacircus.model.Flea obj = dod.getRandomFlea();
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Flea' failed to provide an identifier", id);
        obj = org.ete.fleacircus.model.Flea.findFlea(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Flea' with identifier '" + id + "'", org.ete.fleacircus.model.Flea.findFlea(id));
    }
    
}
