// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.ete.fleacircus.model;

import java.util.List;
import java.util.Random;
import org.ete.fleacircus.model.Specialty;
import org.springframework.stereotype.Component;

privileged aspect SpecialtyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SpecialtyDataOnDemand: @Component;
    
    private Random SpecialtyDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Specialty> SpecialtyDataOnDemand.data;
    
    public Specialty SpecialtyDataOnDemand.getNewTransientSpecialty(int index) {
        org.ete.fleacircus.model.Specialty obj = new org.ete.fleacircus.model.Specialty();
        setName(obj, index);
        return obj;
    }
    
    private void SpecialtyDataOnDemand.setName(Specialty obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    public Specialty SpecialtyDataOnDemand.getSpecificSpecialty(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Specialty obj = data.get(index);
        return Specialty.findSpecialty(obj.getId());
    }
    
    public Specialty SpecialtyDataOnDemand.getRandomSpecialty() {
        init();
        Specialty obj = data.get(rnd.nextInt(data.size()));
        return Specialty.findSpecialty(obj.getId());
    }
    
    public boolean SpecialtyDataOnDemand.modifySpecialty(Specialty obj) {
        return false;
    }
    
    public void SpecialtyDataOnDemand.init() {
        data = org.ete.fleacircus.model.Specialty.findSpecialtyEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Specialty' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.ete.fleacircus.model.Specialty>();
        for (int i = 0; i < 10; i++) {
            org.ete.fleacircus.model.Specialty obj = getNewTransientSpecialty(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
